# Generated by Django 4.2.7 on 2023-11-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_alter_habit_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='periodicity',
            field=models.IntegerField(default=1, max_length=1, verbose_name='периодичность в днях'),
        ),
    ]
