# Generated by Django 4.2.7 on 2023-11-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_alter_habit_periodicity'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='date_of_next_reminder_sending',
            field=models.DateField(blank=True, null=True, verbose_name='дата отправки следующего напоминания'),
        ),
    ]
