# Generated by Django 4.2.7 on 2023-11-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0007_habit_date_of_next_reminder_sending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='periodicity',
            field=models.PositiveIntegerField(default=1, verbose_name='периодичность в днях'),
        ),
    ]
